# --- Configuração de Conexão com o PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/db_caimbe
spring.datasource.username=postgres
spring.datasource.password=sua_senha_aqui

# --- Driver do Banco de Dados ---
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configurações do Hibernate / JPA ---
# O 'update' faz o Hibernate criar as tabelas ou atualizar colunas automaticamente quando o app roda
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do VS Code/IntelliJ as consultas SQL reais que o Java está fazendo no banco (ótimo para estudos!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o Hibernate use o dialeto correto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect